// Static thumbnail mappings for exercise list performance
// Maps exercise ID to local thumbnail asset

export const staticThumbnails: { [key: string]: any } = {
  '1': require('../../assets/exercise-thumbnails/abdominals/alternate-heel-touches.jpg'), // 얼터네이트 힐 터치,
  '2': require('../../assets/exercise-thumbnails/abdominals/body-saw-plank.jpg'), // 바디 소 플랭크,
  '3': require('../../assets/exercise-thumbnails/abdominals/captains-chair-leg-raise.jpg'), // 캡틴스 체어 레그 레이즈,
  '4': require('../../assets/exercise-thumbnails/abdominals/knee-touch-crunch.jpg'), // 니 터치 크런치,
  '5': require('../../assets/exercise-thumbnails/abdominals/tuck-crunch.jpg'), // 턱 크런치,
  '6': require('../../assets/exercise-thumbnails/back/assisted-pull-ups.jpg'), // 어시스트 풀업,
  '7': require('../../assets/exercise-thumbnails/back/band-pull-apart.jpg'), // 밴드 풀 어파트,
  '9': require('../../assets/exercise-thumbnails/back/banded-face-pull.jpg'), // 밴드 페이스 풀,
  '10': require('../../assets/exercise-thumbnails/back/barbell-pendlay-row.jpg'), // 바벨 펜들레이 로우,
  '11': require('../../assets/exercise-thumbnails/back/barbell-pullover.jpg'), // 바벨 풀오버,
  '12': require('../../assets/exercise-thumbnails/back/barbell-row.jpg'), // 바벨 로우,
  '13': require('../../assets/exercise-thumbnails/back/behind-neck-pulldown.jpg'), // 비하인드 넥 풀다운,
  '14': require('../../assets/exercise-thumbnails/back/bent-over-dumbbell-row.jpg'), // 벤트오버 덤벨 로우,
  '15': require('../../assets/exercise-thumbnails/back/cable-face-pull.jpg'), // 케이블 페이스 풀,
  '16': require('../../assets/exercise-thumbnails/back/cable-pullover.jpg'), // 케이블 풀오버,
  '17': require('../../assets/exercise-thumbnails/back/cable-rope-arm-pulldown.jpg'), // 케이블 로프 암 풀다운,
  '18': require('../../assets/exercise-thumbnails/back/cable-row.jpg'), // 케이블 로우,
  '19': require('../../assets/exercise-thumbnails/back/cable-seated-row.jpg'), // 케이블 시티드 로우,
  '20': require('../../assets/exercise-thumbnails/back/chest-supported-barbell-row.jpg'), // 체스트 서포티드 바벨 로우,
  '21': require('../../assets/exercise-thumbnails/back/chest-supported-dumbbell-row.jpg'), // 체스트 서포티드 덤벨 로우,
  '22': require('../../assets/exercise-thumbnails/back/chest-supported-t-bar-row-machine.jpg'), // 체스트 서포티드 T바 로우 머신,
  '23': require('../../assets/exercise-thumbnails/back/chin-up.jpg'), // 친업,
  '24': require('../../assets/exercise-thumbnails/back/close-grip-lat-pulldown.jpg'), // 클로즈 그립 랫 풀다운,
  '26': require('../../assets/exercise-thumbnails/back/dead-hang.jpg'), // 데드 행,
  '27': require('../../assets/exercise-thumbnails/back/dumbbell-face-pull.jpg'), // 덤벨 페이스 풀,
  '29': require('../../assets/exercise-thumbnails/back/dumbbell-row.jpg'), // 덤벨 로우,
  '30': require('../../assets/exercise-thumbnails/back/face-pull.jpg'), // 페이스 풀,
  '31': require('../../assets/exercise-thumbnails/back/inverted-row.jpg'), // 인버티드 로우,
  '32': require('../../assets/exercise-thumbnails/back/jumping_pull_ups.jpg'), // 점핑 풀 업스,
  '33': require('../../assets/exercise-thumbnails/back/kettlebell-upright-row.jpg'), // 케틀벨 업라이트 로우,
  '37': require('../../assets/exercise-thumbnails/back/machine-high-row.jpg'), // 머신 하이 로우,
  '38': require('../../assets/exercise-thumbnails/back/machine-pullover.jpg'), // 머신 풀오버,
  '39': require('../../assets/exercise-thumbnails/back/machine-seated-row.jpg'), // 머신 시티드 로우,
  '40': require('../../assets/exercise-thumbnails/back/machine-t-bar-row.jpg'), // 머신 T바 로우,
  '41': require('../../assets/exercise-thumbnails/back/machine-wide-pulldown.jpg'), // 머신 와이드 풀다운,
  '42': require('../../assets/exercise-thumbnails/back/negative-pull-up.jpg'), // 네거티브 풀업,
  '43': require('../../assets/exercise-thumbnails/back/neutral-grip-lat-pulldown.jpg'), // 뉴트럴 그립 랫 풀다운,
  '44': require('../../assets/exercise-thumbnails/back/neutral-grip-pull-up.jpg'), // 뉴트럴 그립 풀업,
  '45': require('../../assets/exercise-thumbnails/back/plate-row.jpg'), // 플레이트 로우,
  '46': require('../../assets/exercise-thumbnails/back/pull-up.jpg'), // 풀업,
  '49': require('../../assets/exercise-thumbnails/back/rowing-machine.jpg'), // 로잉 머신,
  '51': require('../../assets/exercise-thumbnails/back/single-arm-landmine-row.jpg'), // 싱글 암 랜드마인 로우,
  '52': require('../../assets/exercise-thumbnails/back/single-arm-lat-pulldown.jpg'), // 싱글 암 랫 풀다운,
  '53': require('../../assets/exercise-thumbnails/back/smith-barbell-row.jpg'), // 스미스 바벨 로우,
  '54': require('../../assets/exercise-thumbnails/back/standing-straight-arm-lat-pulldown.jpg'), // 스탠딩 스트레이트 암 랫 풀다운,
  '55': require('../../assets/exercise-thumbnails/back/t-bar-row.jpg'), // T바 로우,
  '56': require('../../assets/exercise-thumbnails/back/underhand-barbell-row.jpg'), // 언더핸드 바벨 로우,
  '60': require('../../assets/exercise-thumbnails/biceps/barbell-bicep-curl.jpg'), // 바벨 컬,
  '61': require('../../assets/exercise-thumbnails/biceps/barbell-cheat-curl.jpg'), // 바벨 치트 컬,
  '62': require('../../assets/exercise-thumbnails/biceps/barbell-preacher-curl.jpg'), // 바벨 프리처 컬,
  '63': require('../../assets/exercise-thumbnails/biceps/cable-bicep-curl.jpg'), // 케이블 바이셉 컬,
  '64': require('../../assets/exercise-thumbnails/biceps/cable-double-bicep-curl.jpg'), // 케이블 더블 바이셉 컬,
  '65': require('../../assets/exercise-thumbnails/biceps/cable-drag-curl.jpg'), // 케이블 드래그 컬,
  '66': require('../../assets/exercise-thumbnails/biceps/cable-rope-bicep-curl.jpg'), // 케이블 로프 바이셉 컬,
  '68': require('../../assets/exercise-thumbnails/biceps/crossbody-hammer-curl.jpg'), // 크로스바디 해머 컬,
  '71': require('../../assets/exercise-thumbnails/biceps/dumbbell-concentration-curl.jpg'), // 덤벨 컨센트레이션 컬,
  '72': require('../../assets/exercise-thumbnails/biceps/dumbbell-hammer-curl.jpg'), // 덤벨 해머 컬,
  '73': require('../../assets/exercise-thumbnails/biceps/ez-bar-bicep-curl.jpg'), // EZ바 바이셉 컬,
  '74': require('../../assets/exercise-thumbnails/biceps/ez-bar-reverse-bicep-curl.jpg'), // EZ바 리버스 바이셉 컬,
  '77': require('../../assets/exercise-thumbnails/biceps/incline-dumbbell-curl.jpg'), // 인클라인 덤벨 컬,
  '78': require('../../assets/exercise-thumbnails/biceps/incline-hammer-curls.jpg'), // 인클라인 해머 컬,
  '79': require('../../assets/exercise-thumbnails/biceps/inner-biceps-curl.jpg'), // 이너 바이셉 컬,
  '81': require('../../assets/exercise-thumbnails/biceps/single-arm-cable-bicep-curl.jpg'), // 싱글 암 케이블 바이셉 컬,
  '82': require('../../assets/exercise-thumbnails/biceps/single-arm-dumbbell-preacher-curl.jpg'), // 싱글 암 덤벨 프리처 컬,
  '83': require('../../assets/exercise-thumbnails/biceps/spider-bicep-curl.jpg'), // 스파이더 바이셉 컬,
  '86': require('../../assets/exercise-thumbnails/biceps/wide-grip-barbell-curl.jpg'), // 와이드 그립 바벨 컬,
  '87': require('../../assets/exercise-thumbnails/biceps/zottman-curl.jpg'), // 조트만 컬,
  '89': require('../../assets/exercise-thumbnails/calves/leg-press-calf-raise-2.jpg'), // 레그 프레스 카프 레이즈,
  '91': require('../../assets/exercise-thumbnails/calves/seated-calf-raise-2.jpg'), // 시티드 카프 레이즈,
  '93': require('../../assets/exercise-thumbnails/calves/single-leg-calf-raise.jpg'), // 싱글 레그 카프 레이즈,
  '94': require('../../assets/exercise-thumbnails/calves/smith-machine-calf-raise.jpg'), // 스미스 머신 카프 레이즈,
  '95': require('../../assets/exercise-thumbnails/calves/standing-calf-raise.jpg'), // 스탠딩 카프 레이즈,
  '114': require('../../assets/exercise-thumbnails/deltoids/arnold-press.jpg'), // 아놀드 프레스,
  '115': require('../../assets/exercise-thumbnails/deltoids/barbell-front-raise.jpg'), // 바벨 프론트 레이즈,
  '116': require('../../assets/exercise-thumbnails/deltoids/barbell-push-press.jpg'), // 바벨 푸시 프레스,
  '117': require('../../assets/exercise-thumbnails/deltoids/barbell-shoulder-press.jpg'), // 바벨 숄더 프레스,
  '118': require('../../assets/exercise-thumbnails/deltoids/cable-front-raise.jpg'), // 케이블 프론트 레이즈,
  '119': require('../../assets/exercise-thumbnails/deltoids/cable-kneeling-shoulder-press.jpg'), // 케이블 닐링 숄더 프레스,
  '120': require('../../assets/exercise-thumbnails/deltoids/cable-rear-delt-row.jpg'), // 케이블 리어 델트 로우,
  '121': require('../../assets/exercise-thumbnails/deltoids/dumbbell-bent-over-lateral-raise.jpg'), // 덤벨 벤트 오버 래터럴 레이즈,
  '122': require('../../assets/exercise-thumbnails/deltoids/dumbbell-lateral-raise.jpg'), // 덤벨 래터럴 레이즈,
  '123': require('../../assets/exercise-thumbnails/deltoids/dumbbell-push-press.jpg'), // 덤벨 푸시 프레스,
  '124': require('../../assets/exercise-thumbnails/deltoids/dumbbell-rear-delt-raise.jpg'), // 덤벨 리어 델트 레이즈,
  '125': require('../../assets/exercise-thumbnails/deltoids/handstand-push-up.jpg'), // 핸드스탠드 푸시업,
  '126': require('../../assets/exercise-thumbnails/deltoids/incline-leaning-dumbbell-lateral-raise.jpg'), // 인클라인 리닝 덤벨 래터럴 레이즈,
  '127': require('../../assets/exercise-thumbnails/deltoids/landmine-press.jpg'), // 랜드마인 프레스,
  '128': require('../../assets/exercise-thumbnails/deltoids/leaning-single-arm-dumbbell-lateral-raise.jpg'), // 리닝 싱글 암 덤벨 래터럴 레이즈,
  '129': require('../../assets/exercise-thumbnails/deltoids/machine-lateral-raise-2.jpg'), // 머신 래터럴 레이즈 2,
  '130': require('../../assets/exercise-thumbnails/deltoids/machine-lateral-raise.jpg'), // 머신 래터럴 레이즈,
  '131': require('../../assets/exercise-thumbnails/deltoids/machine-rear-delt-fly.jpg'), // 머신 리어 델트 플라이,
  '132': require('../../assets/exercise-thumbnails/deltoids/machine-shoulder-press-2.jpg'), // 머신 숄더 프레스 2,
  '133': require('../../assets/exercise-thumbnails/deltoids/machine-shoulder-press.jpg'), // 머신 숄더 프레스,
  '134': require('../../assets/exercise-thumbnails/deltoids/military_press.jpg'), // 밀리터리 프레스,
  '135': require('../../assets/exercise-thumbnails/deltoids/military-press.jpg'), // 밀리터리 프레스,
  '136': require('../../assets/exercise-thumbnails/deltoids/pike-push-up.jpg'), // 파이크 푸시업,
  '137': require('../../assets/exercise-thumbnails/deltoids/plate-front-raise.jpg'), // 플레이트 프론트 레이즈,
  '138': require('../../assets/exercise-thumbnails/deltoids/prone-y-raises.jpg'), // 프론트 Y 레이즈,
  '139': require('../../assets/exercise-thumbnails/deltoids/seated-barbell-shoulder-press.jpg'), // 시티드 바벨 숄더 프레스,
  '140': require('../../assets/exercise-thumbnails/deltoids/seated-dumbbell-front-raise.jpg'), // 시티드 덤벨 프론트 레이즈,
  '141': require('../../assets/exercise-thumbnails/deltoids/seated-dumbbell-lateral-raise.jpg'), // 시티드 덤벨 래터럴 레이즈,
  '142': require('../../assets/exercise-thumbnails/deltoids/seated-dumbbell-shoulder-press.jpg'), // 시티드 덤벨 숄더 프레스,
  '143': require('../../assets/exercise-thumbnails/deltoids/seated-ez-bar-front-raise.jpg'), // 시티드 EZ바 프론트 레이즈,
  '144': require('../../assets/exercise-thumbnails/deltoids/seated-smith-shoulder-press.jpg'), // 시티드 스미스 숄더 프레스,
  '145': require('../../assets/exercise-thumbnails/deltoids/shoulder-push-up.jpg'), // 숄더 푸시업,
  '146': require('../../assets/exercise-thumbnails/deltoids/single-arm-cable-lateral-raise.jpg'), // 싱글 암 케이블 래터럴 레이즈,
  '147': require('../../assets/exercise-thumbnails/deltoids/single-arm-cable-lateral-raises.jpg'), // 싱글 암 케이블 래터럴 레이즈,
  '148': require('../../assets/exercise-thumbnails/deltoids/single-arm-dumbbell-shoulder-press.jpg'), // 싱글 암 덤벨 숄더 프레스,
  '149': require('../../assets/exercise-thumbnails/deltoids/smith-behind-neck-shoulder-press.jpg'), // 스미스 비하인드 넥 숄더 프레스,
  '150': require('../../assets/exercise-thumbnails/deltoids/standing-smith-shoulder-press.jpg'), // 스탠딩 스미스 숄더 프레스,
  '151': require('../../assets/exercise-thumbnails/deltoids/upright_row.jpg'), // 업라이트 로우,
  '152': require('../../assets/exercise-thumbnails/forearms/barbell-reverse-wrist-curl.jpg'), // 바벨 리버스 리스트 컬,
  '153': require('../../assets/exercise-thumbnails/forearms/barbell-wrist-curl.jpg'), // 바벨 리스트 컬,
  '154': require('../../assets/exercise-thumbnails/forearms/dumbbell-reverse-wrist-curl.jpg'), // 덤벨 리버스 리스트 컬,
  '155': require('../../assets/exercise-thumbnails/forearms/dumbbell-wrist-curl.jpg'), // 덤벨 리스트 컬,
  '159': require('../../assets/exercise-thumbnails/forearms/wrist-push-up.jpg'), // 리스트 푸시업,
  '160': require('../../assets/exercise-thumbnails/glutes/banded-hip-thrust.jpg'), // 밴드 힙 스러스트,
  '161': require('../../assets/exercise-thumbnails/glutes/barbell-hip-thrust.jpg'), // 바벨 힙 스러스트,
  '162': require('../../assets/exercise-thumbnails/glutes/cable-hip-adduction.jpg'), // 케이블 힙 어덕션,
  '163': require('../../assets/exercise-thumbnails/glutes/cable-pull-through.jpg'), // 케이블 풀 스루,
  '164': require('../../assets/exercise-thumbnails/glutes/dumbbell-glute-bridge.jpg'), // 덤벨 글루트 브릿지,
  '166': require('../../assets/exercise-thumbnails/glutes/elevated-glute-bridge.jpg'), // 엘리베이티드 글루트 브릿지,
  '167': require('../../assets/exercise-thumbnails/glutes/frog-hip-thrust.jpg'), // 프로그 힙 스러스트,
  '169': require('../../assets/exercise-thumbnails/glutes/glute-kickback-machine.jpg'), // 글루트 킥백 머신,
  '170': require('../../assets/exercise-thumbnails/glutes/hip-abduction.jpg'), // 힙 어브덕션,
  '172': require('../../assets/exercise-thumbnails/glutes/machine-standing-hip-abduction.jpg'), // 머신 스탠딩 힙 어브덕션,
  '173': require('../../assets/exercise-thumbnails/glutes/resistance-band-glute-bridge.jpg'), // 레지스턴스 밴드 글루트 브릿지,
  '174': require('../../assets/exercise-thumbnails/glutes/single-leg-cable-kickback.jpg'), // 싱글 레그 케이블 킥백,
  '175': require('../../assets/exercise-thumbnails/glutes/single-leg-hip-thrust.jpg'), // 싱글 레그 힙 스러스트,
  '176': require('../../assets/exercise-thumbnails/glutes/smith-machine-hip-thrust.jpg'), // 스미스 머신 힙 쓰러스트,
  '177': require('../../assets/exercise-thumbnails/hamstrings/barbell_deadlift.jpg'), // 바벨 데드리프트,
  '178': require('../../assets/exercise-thumbnails/hamstrings/barbell-good-morning.jpg'), // 바벨 굿모닝,
  '180': require('../../assets/exercise-thumbnails/hamstrings/deficit-deadlift.jpg'), // 디피싯 데드리프트,
  '181': require('../../assets/exercise-thumbnails/hamstrings/dumbbell-stiff-leg-deadlift.jpg'), // 덤벨 스티프 레그 데드리프트,
  '184': require('../../assets/exercise-thumbnails/hamstrings/kettlebell-sumo-deadlift.jpg'), // 케틀벨 스모 데드리프트,
  '185': require('../../assets/exercise-thumbnails/hamstrings/kneeling-leg-curl.jpg'), // 닐링 레그 컬,
  '186': require('../../assets/exercise-thumbnails/hamstrings/landmine-deadlift.jpg'), // 랜드마인 데드리프트,
  '187': require('../../assets/exercise-thumbnails/hamstrings/lying-leg-curl.jpg'), // 라잉 레그 컬,
  '189': require('../../assets/exercise-thumbnails/hamstrings/nordic-curl.jpg'), // 노르딕 컬,
  '194': require('../../assets/exercise-thumbnails/hamstrings/seated-leg-curl.jpg'), // 시티드 레그 컬,
  '195': require('../../assets/exercise-thumbnails/hamstrings/single-leg-curl.jpg'), // 싱글 레그 컬,
  '196': require('../../assets/exercise-thumbnails/hamstrings/stiff-leg-deadlift.jpg'), // 스티프 레그 데드리프트,
  '198': require('../../assets/exercise-thumbnails/hamstrings/suitcase-deadlift.jpg'), // 수트케이스 데드리프트,
  '201': require('../../assets/exercise-thumbnails/pectorals/assisted-dips.jpg'), // 어시스티드 딥스,
  '204': require('../../assets/exercise-thumbnails/pectorals/barbell-bench-press.jpg'), // 바벨 벤치 프레스,
  '205': require('../../assets/exercise-thumbnails/pectorals/barbell-decline-bench-press.jpg'), // 바벨 디클라인 벤치 프레스,
  '206': require('../../assets/exercise-thumbnails/pectorals/bench-dips.jpg'), // 벤치 딥스,
  '207': require('../../assets/exercise-thumbnails/pectorals/board-bench-press.jpg'), // 보드 벤치 프레스,
  '208': require('../../assets/exercise-thumbnails/pectorals/cable-chest-fly.jpg'), // 케이블 체스트 플라이,
  '211': require('../../assets/exercise-thumbnails/pectorals/chest-press-machine.jpg'), // 체스트 프레스 머신,
  '214': require('../../assets/exercise-thumbnails/pectorals/decline-barbell-bench-press.jpg'), // 디클라인 바벨 벤치 프레스,
  '215': require('../../assets/exercise-thumbnails/pectorals/decline-cable-fly.jpg'), // 디클라인 케이블 플라이,
  '216': require('../../assets/exercise-thumbnails/pectorals/decline-dumbbell-fly.jpg'), // 디클라인 덤벨 플라이,
  '217': require('../../assets/exercise-thumbnails/pectorals/deficit-push-ups.jpg'), // 디피싯 푸시업,
  '220': require('../../assets/exercise-thumbnails/pectorals/dips.jpg'), // 딥스,
  '221': require('../../assets/exercise-thumbnails/pectorals/dumbbell-bench-press.jpg'), // 덤벨 벤치 프레스,
  '222': require('../../assets/exercise-thumbnails/pectorals/dumbbell-chest-fly.jpg'), // 덤벨 체스트 플라이,
  '223': require('../../assets/exercise-thumbnails/pectorals/dumbbell-close-grip-press.jpg'), // 덤벨 클로즈 그립 프레스,
  '224': require('../../assets/exercise-thumbnails/pectorals/finger_pushups.jpg'), // 핑거 푸시업,
  '225': require('../../assets/exercise-thumbnails/pectorals/floor-press.jpg'), // 플로어 프레스,
  '226': require('../../assets/exercise-thumbnails/pectorals/hex_press.jpg'), // 헥스 프레스,
  '228': require('../../assets/exercise-thumbnails/pectorals/incline-barbell-bench-press.jpg'), // 인클라인 바벨 벤치 프레스,
  '229': require('../../assets/exercise-thumbnails/pectorals/incline-dumbbell-fly.jpg'), // 인클라인 덤벨 플라이,
  '230': require('../../assets/exercise-thumbnails/pectorals/incline-push-up.jpg'), // 인클라인 푸시업,
  '231': require('../../assets/exercise-thumbnails/pectorals/knee-push-up.jpg'), // 니 푸시업,
  '232': require('../../assets/exercise-thumbnails/pectorals/knuckle_pushups.jpg'), // 너클 푸시업,
  '233': require('../../assets/exercise-thumbnails/pectorals/machine-chest-fly.jpg'), // 머신 체스트 플라이,
  '234': require('../../assets/exercise-thumbnails/pectorals/machine-chest-press.jpg'), // 머신 체스트 프레스,
  '235': require('../../assets/exercise-thumbnails/pectorals/machine-dips.jpg'), // 머신 딥스,
  '237': require('../../assets/exercise-thumbnails/pectorals/parallel-dips.jpg'), // 패러렐 딥스,
  '238': require('../../assets/exercise-thumbnails/pectorals/pec-dec-fly.jpg'), // 펙 덱 플라이,
  '240': require('../../assets/exercise-thumbnails/pectorals/pin-press.jpg'), // 핀 프레스,
  '241': require('../../assets/exercise-thumbnails/pectorals/plate-chest-press.jpg'), // 플레이트 체스트 프레스,
  '242': require('../../assets/exercise-thumbnails/pectorals/plyometric-push-up.jpg'), // 플라이오메트릭 푸시업,
  '243': require('../../assets/exercise-thumbnails/pectorals/push-ups-with-rotation.jpg'), // 로테이션 푸시업,
  '244': require('../../assets/exercise-thumbnails/pectorals/resistance-band-push-up.jpg'), // 레지스턴스 밴드 푸시업,
  '245': require('../../assets/exercise-thumbnails/pectorals/single-arm-dumbbell-press.jpg'), // 싱글 암 덤벨 프레스,
  '246': require('../../assets/exercise-thumbnails/pectorals/smith-bench-press.jpg'), // 스미스 벤치 프레스,
  '247': require('../../assets/exercise-thumbnails/pectorals/sphinx-push-up.jpg'), // 스핑크스 푸시업,
  '249': require('../../assets/exercise-thumbnails/pectorals/svend-press.jpg'), // 스벤드 프레스,
  '251': require('../../assets/exercise-thumbnails/pectorals/weighted-push-up.jpg'), // 웨이티드 푸시업,
  '255': require('../../assets/exercise-thumbnails/quadriceps/barbell-bulgarian-split-squat.jpg'), // 바벨 불가리안 스플릿 스쿼트,
  '256': require('../../assets/exercise-thumbnails/quadriceps/barbell-front-squat.jpg'), // 바벨 프론트 스쿼트,
  '257': require('../../assets/exercise-thumbnails/quadriceps/barbell-lunge.jpg'), // 바벨 런지,
  '258': require('../../assets/exercise-thumbnails/quadriceps/barbell-sumo-squat.jpg'), // 바벨 스모 스쿼트,
  '259': require('../../assets/exercise-thumbnails/quadriceps/belt-squat.jpg'), // 벨트 스쿼트,
  '260': require('../../assets/exercise-thumbnails/quadriceps/bodyweight-lunge.jpg'), // 바디웨이트 런지,
  '261': require('../../assets/exercise-thumbnails/quadriceps/bodyweight-squat.jpg'), // 바디웨이트 스쿼트,
  '263': require('../../assets/exercise-thumbnails/quadriceps/bulgarian-split-squat.jpg'), // 불가리안 스플릿 스쿼트,
  '264': require('../../assets/exercise-thumbnails/quadriceps/deficit-reverse-lunge.jpg'), // 디피싯 리버스 런지,
  '265': require('../../assets/exercise-thumbnails/quadriceps/dumbbell-front-squat.jpg'), // 덤벨 프론트 스쿼트,
  '266': require('../../assets/exercise-thumbnails/quadriceps/dumbbell-hack-squat.jpg'), // 덤벨 핵 스쿼트,
  '268': require('../../assets/exercise-thumbnails/quadriceps/dumbbell-squat.jpg'), // 덤벨 스쿼트,
  '269': require('../../assets/exercise-thumbnails/quadriceps/dumbbell-sumo-squat.jpg'), // 덤벨 스모 스쿼트,
  '270': require('../../assets/exercise-thumbnails/quadriceps/frog-squat.jpg'), // 프로그 스쿼트,
  '273': require('../../assets/exercise-thumbnails/quadriceps/gym-ball-squat.jpg'), // 짐볼 스쿼트,
  '275': require('../../assets/exercise-thumbnails/quadriceps/hack-squat.jpg'), // 핵 스쿼트,
  '276': require('../../assets/exercise-thumbnails/quadriceps/half-knee-bends.jpg'), // 하프 니 벤드,
  '277': require('../../assets/exercise-thumbnails/quadriceps/kettlebell-squat-clean.jpg'), // 케틀벨 스쿼트 클린,
  '278': require('../../assets/exercise-thumbnails/quadriceps/kettlebell-squat.jpg'), // 케틀벨 스쿼트,
  '281': require('../../assets/exercise-thumbnails/quadriceps/landmine-squat.jpg'), // 랜드마인 스쿼트,
  '282': require('../../assets/exercise-thumbnails/quadriceps/leg-extension-2.jpg'), // 레그 익스텐션,
  '284': require('../../assets/exercise-thumbnails/quadriceps/low-bar-squat.jpg'), // 로우바 스쿼트,
  '285': require('../../assets/exercise-thumbnails/quadriceps/lunges.jpg'), // 런지,
  '286': require('../../assets/exercise-thumbnails/quadriceps/machine-leg-press.jpg'), // 머신 레그 프레스,
  '287': require('../../assets/exercise-thumbnails/quadriceps/negative_squat.jpg'), // 네거티브 스쿼트,
  '288': require('../../assets/exercise-thumbnails/quadriceps/overhead-squat.jpg'), // 오버헤드 스쿼트,
  '289': require('../../assets/exercise-thumbnails/quadriceps/pistol-squat.jpg'), // 피스톨 스쿼트,
  '290': require('../../assets/exercise-thumbnails/quadriceps/resistance-band-lunge.jpg'), // 레지스턴스 밴드 런지,
  '291': require('../../assets/exercise-thumbnails/quadriceps/reverse-squat.jpg'), // 리버스 스쿼트,
  '292': require('../../assets/exercise-thumbnails/quadriceps/reverse-v-squat.jpg'), // 리버스 V 스쿼트,
  '293': require('../../assets/exercise-thumbnails/quadriceps/seated-knee-extension.jpg'), // 시티드 니 익스텐션,
  '294': require('../../assets/exercise-thumbnails/quadriceps/shrimp-squat.jpg'), // 쉬림프 스쿼트,
  '295': require('../../assets/exercise-thumbnails/quadriceps/single-leg-extension.jpg'), // 싱글 레그 익스텐션,
  '296': require('../../assets/exercise-thumbnails/quadriceps/single-leg-press.jpg'), // 싱글 레그 프레스,
  '298': require('../../assets/exercise-thumbnails/quadriceps/smith-machine-lunge.jpg'), // 스미스 머신 런지,
  '302': require('../../assets/exercise-thumbnails/quadriceps/step-ups.jpg'), // 스텝 업,
  '304': require('../../assets/exercise-thumbnails/quadriceps/tempo_squats.jpg'), // 템포 스쿼트,
  '321': require('../../assets/exercise-thumbnails/triceps/barbell-incline-tricep-extension.jpg'), // 바벨 인클라인 트라이셉 익스텐션,
  '322': require('../../assets/exercise-thumbnails/triceps/barbell-lying-tricep-extension.jpg'), // 바벨 라잉 트라이셉 익스텐션,
  '323': require('../../assets/exercise-thumbnails/triceps/barbell-tricep-extension.jpg'), // 바벨 트라이셉 익스텐션,
  '324': require('../../assets/exercise-thumbnails/triceps/cable-incline-tricep-extension.jpg'), // 케이블 인클라인 트라이셉 익스텐션,
  '325': require('../../assets/exercise-thumbnails/triceps/cable-overhead-tricep-extension.jpg'), // 케이블 오버헤드 트라이셉 익스텐션,
  '326': require('../../assets/exercise-thumbnails/triceps/cable-pushdown.jpg'), // 케이블 푸시다운,
  '327': require('../../assets/exercise-thumbnails/triceps/cable-reverse-grip-tricep-pushdown.jpg'), // 케이블 리버스 그립 트라이셉 푸시다운,
  '328': require('../../assets/exercise-thumbnails/triceps/cable-rope-tricep-extension.jpg'), // 케이블 로프 트라이셉 익스텐션,
  '329': require('../../assets/exercise-thumbnails/triceps/cable-single-arm-reverse-grip-tricep-pushdown.jpg'), // 케이블 싱글 암 리버스 그립 트라이셉 푸시다운,
  '330': require('../../assets/exercise-thumbnails/triceps/cable-tricep-kickback.jpg'), // 케이블 트라이셉 킥백,
  '331': require('../../assets/exercise-thumbnails/triceps/cable-v-bar-tricep-pushdown.jpg'), // 케이블 V바 트라이셉 푸시다운,
  '333': require('../../assets/exercise-thumbnails/triceps/cobra-push-up.jpg'), // 코브라 푸시업,
  '334': require('../../assets/exercise-thumbnails/triceps/dive-bomber-push-ups.jpg'), // 다이브 봄버 푸시업,
  '335': require('../../assets/exercise-thumbnails/triceps/dumbbell-tricep-extension-2.jpg'), // 덤벨 트라이셉 익스텐션 2,
  '336': require('../../assets/exercise-thumbnails/triceps/dumbbell-tricep-extension.jpg'), // 덤벨 트라이셉 익스텐션,
  '337': require('../../assets/exercise-thumbnails/triceps/dumbbell-tricep-kickback-2.jpg'), // 덤벨 트라이셉 킥백 2,
  '338': require('../../assets/exercise-thumbnails/triceps/dumbbell-tricep-kickback.jpg'), // 덤벨 트라이셉 킥백,
  '339': require('../../assets/exercise-thumbnails/triceps/kneeling-cable-overhead-tricep-extension.jpg'), // 닐링 케이블 오버헤드 트라이셉 익스텐션,
  '340': require('../../assets/exercise-thumbnails/triceps/machine-tricep-extension-2.jpg'), // 머신 트라이셉 익스텐션 2,
  '341': require('../../assets/exercise-thumbnails/triceps/machine-tricep-extension.jpg'), // 머신 트라이셉 익스텐션,
  '342': require('../../assets/exercise-thumbnails/triceps/overhead-tricep-stretch.jpg'), // 오버헤드 트라이셉 스트레치,
  '343': require('../../assets/exercise-thumbnails/triceps/single-arm-cable-tricep-extension.jpg'), // 싱글 암 케이블 트라이셉 익스텐션,
  '344': require('../../assets/exercise-thumbnails/triceps/single-arm-dumbbell-tricep-extension.jpg'), // 싱글 암 덤벨 트라이셉 익스텐션,
  '346': require('../../assets/exercise-thumbnails/triceps/triceps-pushdown.jpg'), // 트라이셉스 푸시다운,
  '347': require('../../assets/exercise-thumbnails/triceps/underhand-tricep-pushdown.jpg'), // 언더핸드 트라이셉 푸시다운,
  '348': require('../../assets/exercise-thumbnails/abdominals/45-degree-extension.jpg'), // 45도 익스텐션,
  '349': require('../../assets/exercise-thumbnails/abdominals/ab-roller.jpg'), // 앱 롤러,
  '350': require('../../assets/exercise-thumbnails/abdominals/decline-sit-up.jpg'), // 디클라인 싯업,
  '351': require('../../assets/exercise-thumbnails/abdominals/leg-raise.jpg'), // 레그 레이즈,
  '352': require('../../assets/exercise-thumbnails/abdominals/mountain-climber.jpg'), // 마운틴 클라이머,
  '353': require('../../assets/exercise-thumbnails/abdominals/machine-crunch.jpg'), // 머신 크런치,
  '354': require('../../assets/exercise-thumbnails/abdominals/bicycle-crunch.jpg'), // 바이시클 크런치,
  '355': require('../../assets/exercise-thumbnails/abdominals/side-plank.jpg'), // 사이드 플랭크,
  '357': require('../../assets/exercise-thumbnails/abdominals/weighted-russian-twist.jpg'), // 중량 러시안 트위스트,
  '358': require('../../assets/exercise-thumbnails/abdominals/weighted-cable-crunch.jpg'), // 중량 케이블 크런치,
  '359': require('../../assets/exercise-thumbnails/abdominals/weighted-plank.jpg'), // 중량 플랭크,
  '360': require('../../assets/exercise-thumbnails/abdominals/captains-chair-knee-raise.jpg'), // 캡틴스 체어 니 레이즈,
  '361': require('../../assets/exercise-thumbnails/abdominals/crunch.jpg'), // 크런치,
  '362': require('../../assets/exercise-thumbnails/abdominals/cross-body-crunch.jpg'), // 크로스 바디 크런치,
  '363': require('../../assets/exercise-thumbnails/abdominals/toes-to-bar.jpg'), // 토즈 투 바,
  '365': require('../../assets/exercise-thumbnails/abdominals/plank.jpg'), // 플랭크,
  '366': require('../../assets/exercise-thumbnails/abdominals/flutter-kick.jpg'), // 플러터 킥,
  '367': require('../../assets/exercise-thumbnails/abdominals/hanging-leg-raise.jpg'), // 행잉 레그 레이즈,
  '368': require('../../assets/exercise-thumbnails/abdominals/sit-up.jpg'), // Sit Up,
  // '370': require('../../assets/exercise-thumbnails/back/back-extension.jpg'), // Back Extension - FILE MISSING
  '371': require('../../assets/exercise-thumbnails/back/lat-pulldown.jpg'), // Lat Pulldown,
  '372': require('../../assets/exercise-thumbnails/back/weighted-pull-up.jpg'), // Weighted Pull Up,
  '373': require('../../assets/exercise-thumbnails/back/wide-grip-lat-pulldown.jpg'), // Wide Grip Lat Pulldown,
  '374': require('../../assets/exercise-thumbnails/back/yates-row.jpg'), // Yates Row,
  '375': require('../../assets/exercise-thumbnails/biceps/dumbbell-bicep-curl.jpg'), // Dumbbell Bicep Curl,
  '376': require('../../assets/exercise-thumbnails/biceps/hammer-curls.jpg'), // Hammer Curls,
  '377': require('../../assets/exercise-thumbnails/biceps/high-pulley-cable-curl.jpg'), // High Pulley Cable Curl,
  '378': require('../../assets/exercise-thumbnails/biceps/preacher-curls.jpg'), // Preacher Curls,
  '379': require('../../assets/exercise-thumbnails/cardio/bike.jpg'), // Bike,
  '380': require('../../assets/exercise-thumbnails/cardio/duck-walk.jpg'), // Duck Walk,
  '381': require('../../assets/exercise-thumbnails/cardio/elliptical-machine.jpg'), // Elliptical Machine,
  '382': require('../../assets/exercise-thumbnails/cardio/step-mill.jpg'), // Step Mill,
  '383': require('../../assets/exercise-thumbnails/cardio/treadmill.jpg'), // Treadmill,
  '384': require('../../assets/exercise-thumbnails/compound/clean-and-press.jpg'), // Clean And Press,
  '385': require('../../assets/exercise-thumbnails/compound/crossfit-cluster.jpg'), // Crossfit Cluster,
  '386': require('../../assets/exercise-thumbnails/compound/dumbbell_devils_press.jpg'), // Dumbbell_devils_press,
  '387': require('../../assets/exercise-thumbnails/compound/dumbbell_push_jerk.jpg'), // Dumbbell_push_jerk,
  '388': require('../../assets/exercise-thumbnails/compound/muscle-up.jpg'), // Muscle Up,
  '389': require('../../assets/exercise-thumbnails/compound/push-jerk.jpg'), // Push Jerk,
  '390': require('../../assets/exercise-thumbnails/compound/ring-muscle-up.jpg'), // Ring Muscle Up,
  '391': require('../../assets/exercise-thumbnails/compound/sled-push.jpg'), // Sled Push,
  '392': require('../../assets/exercise-thumbnails/compound/tire-flip.jpg'), // Tire Flip,
  '393': require('../../assets/exercise-thumbnails/glutes/glute-kickback-hip-extension.jpg'), // Glute Kickback Hip Extension,
  '394': require('../../assets/exercise-thumbnails/glutes/hip-adduction-inner-thigh-machine.jpg'), // Hip Adduction Inner Thigh Machine,
  '395': require('../../assets/exercise-thumbnails/hamstrings/romanian-deadlift.jpg'), // Romanian Deadlift,
  '396': require('../../assets/exercise-thumbnails/hamstrings/sumo-deadlift.jpg'), // Sumo Deadlift,
  '397': require('../../assets/exercise-thumbnails/pectorals/cable-crossover.jpg'), // Cable Crossover,
  '398': require('../../assets/exercise-thumbnails/pectorals/wide_grip_bench_press.jpg'), // Wide_grip_bench_press,
  // '400': require('../../assets/exercise-thumbnails/quadriceps/barbell-squat.jpg'), // Barbell Squat - FILE MISSING
  '401': require('../../assets/exercise-thumbnails/quadriceps/front-squat.jpg'), // Front Squat,
  '403': require('../../assets/exercise-thumbnails/quadriceps/smith-machine-squat-2.jpg'), // Smith Machine Squat 2,
  '404': require('../../assets/exercise-thumbnails/quadriceps/trap-bar-deadlift.jpg'), // Trap Bar Deadlift,
  '405': require('../../assets/exercise-thumbnails/quadriceps/zercher-squat.jpg'), // Zercher Squat,
  '406': require('../../assets/exercise-thumbnails/traps/barbell-shrug.jpg'), // Barbell Shrug,
  '407': require('../../assets/exercise-thumbnails/traps/barbell-upright-row.jpg'), // Barbell Upright Row,
  '408': require('../../assets/exercise-thumbnails/traps/cable-shrug.jpg'), // Cable Shrug,
  '409': require('../../assets/exercise-thumbnails/traps/cable-upright-row.jpg'), // Cable Upright Row,
  '410': require('../../assets/exercise-thumbnails/traps/chest-supported-dumbbell-shrug.jpg'), // Chest Supported Dumbbell Shrug,
  '411': require('../../assets/exercise-thumbnails/traps/dumbbell-shrug.jpg'), // Dumbbell Shrug,
  '412': require('../../assets/exercise-thumbnails/traps/dumbbell-upright-row.jpg'), // Dumbbell Upright Row,
  '413': require('../../assets/exercise-thumbnails/traps/ez-bar-upright-row.jpg'), // Ez Bar Upright Row,
  '414': require('../../assets/exercise-thumbnails/traps/single-arm-dumbbell-upright-row.jpg'), // Single Arm Dumbbell Upright Row,
  '415': require('../../assets/exercise-thumbnails/traps/smith-machine-shrug.jpg'), // Smith Machine Shrug,
  '416': require('../../assets/exercise-thumbnails/triceps/close-grip-bench-press.jpg'), // Close Grip Bench Press,
  // '369': require('../../assets/exercise-thumbnails/back/58_wide-grip-lat-pulldown.jpg'), // 58_wide Grip Lat Pulldown - FILE MISSING
  // '399': require('../../assets/exercise-thumbnails/quadriceps/300_smith-machine-squat-2.jpg'), // 300_smith Machine Squat 2 - FILE MISSING
  // '402': require('../../assets/exercise-thumbnails/quadriceps/leg-press.jpg') // Leg Press - FILE MISSING
};

// Helper function to get thumbnail by exercise ID
export function getStaticThumbnail(exerciseId: number | string): any {
  const id = exerciseId.toString();
  return staticThumbnails[id] || null;
}

// Export both as named and default
export { staticThumbnails };
export default staticThumbnails;
