#!/bin/bash
cd "/mnt/c/Users/PW1234/.vscode/new finess app/new exercises"

mv "45도 익스텐션.gif" "45-degree-extension.gif"
mv "ab 롤러.gif" "ab-roller.gif"
mv "디클라인 싯업.gif" "decline-sit-up.gif"
mv "레그 레이즈.gif" "leg-raise.gif"
mv "마운틴 클라이머.gif" "mountain-climber.gif"
mv "머신 크런치.gif" "machine-crunch.gif"
mv "바이시클 크런치.gif" "bicycle-crunch.gif"
mv "사이드 플랭크.gif" "side-plank.gif"
mv "싯 업.gif" "sit-up.gif"
mv "중량 러시안 트위스트.gif" "weighted-russian-twist.gif"
mv "중량 케이블 크런치.gif" "weighted-cable-crunch.gif"
mv "중량 플랭크.gif" "weighted-plank.gif"
mv "캡틴스 체어 니 레이즈.gif" "captains-chair-knee-raise.gif"
mv "크런치.gif" "crunch.gif"
mv "크로스 바디 크런치.gif" "cross-body-crunch.gif"
mv "토즈 투 바.gif" "toes-to-bar.gif"
mv "푸시업.gif" "push-up.gif"
mv "플랭크.gif" "plank.gif"
mv "플러터 킥.gif" "flutter-kick.gif"
mv "행잉 레그 레이즈.gif" "hanging-leg-raise.gif"
